import { StyleSheet } from 'react-native';

import { colors, radii, spacing } from '@/lib/shared/theme';

/** Shared look for the Records screens. Same tokens as the statement panels. */
export const rs = StyleSheet.create({
  root: { gap: 16 },
  pageHeader: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    paddingHorizontal: 18,
    paddingVertical: 18,
    gap: 4,
  },
  pageTitle: {
    fontSize: 26,
    fontWeight: '900',
    color: colors.textStrong,
    letterSpacing: -0.4,
  },
  pageCircleName: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.primaryDark,
    marginTop: 2,
  },
  pageDisclaimer: { fontSize: 11, color: colors.subtle, marginTop: 6, lineHeight: 16 },

  segmentStrip: {
    gap: 6,
    paddingVertical: 2,
  },
  segmentPill: {
    minHeight: 40,
    borderRadius: radii.pill,
    paddingHorizontal: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.surfaceMuted,
  },
  segmentPillActive: { backgroundColor: colors.primary },
  segmentPillLabel: { fontSize: 13, fontWeight: '800', color: colors.muted },
  segmentPillLabelActive: { color: colors.onColor },

  panel: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 16,
    gap: 12,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: colors.textStrong,
    letterSpacing: -0.2,
  },
  sectionLabel: {
    fontSize: 12,
    fontWeight: '800',
    color: colors.muted,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  roundHeading: {
    fontSize: 13,
    fontWeight: '900',
    color: colors.primaryDark,
    marginTop: 4,
  },

  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceMuted,
  },
  rowLast: { borderBottomWidth: 0 },
  rowMain: { flex: 1, minWidth: 0 },
  rowTitle: { fontSize: 14, fontWeight: '800', color: colors.textStrong },
  rowMeta: { fontSize: 12, color: colors.muted, marginTop: 2, lineHeight: 16 },
  rowReference: { fontSize: 11, color: colors.subtle, marginTop: 2, letterSpacing: 0.3 },
  rowRight: { alignItems: 'flex-end', gap: 6 },
  rowAmount: { fontSize: 14, fontWeight: '800', color: colors.textStrong },

  chip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 3,
    alignSelf: 'flex-start',
  },
  chipText: { fontSize: 11, fontWeight: '800' },

  filterStrip: { gap: 6, paddingBottom: 2 },
  filterChip: {
    minHeight: 36,
    borderRadius: radii.pill,
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
    backgroundColor: colors.card,
  },
  filterChipActive: { backgroundColor: colors.primarySoft, borderColor: colors.primaryBorder },
  filterChipText: { fontSize: 12, fontWeight: '700', color: colors.muted },
  filterChipTextActive: { color: colors.primaryDark },

  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  metric: {
    flexGrow: 1,
    flexBasis: '45%',
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 12,
  },
  metricLabel: { fontSize: 12, fontWeight: '600', color: colors.muted },
  metricValue: { fontSize: 18, fontWeight: '900', color: colors.textStrong, marginTop: 2 },

  noticeCard: {
    backgroundColor: colors.warningSoft,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.warningBorder,
    padding: 16,
    gap: 10,
  },
  noticeText: { fontSize: 14, fontWeight: '800', color: colors.warningText },
  calmText: { fontSize: 13, color: colors.muted, lineHeight: 19 },

  stateCard: {
    backgroundColor: colors.background,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 20,
    alignItems: 'center',
    gap: 8,
  },
  stateTitle: { fontSize: 15, fontWeight: '800', color: colors.textStrong, textAlign: 'center' },
  stateBody: { fontSize: 13, color: colors.muted, textAlign: 'center', lineHeight: 19 },

  primaryBtn: {
    minHeight: 48,
    backgroundColor: colors.primary,
    borderRadius: radii.pill,
    paddingHorizontal: 20,
    paddingVertical: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  primaryBtnText: { color: colors.onColor, fontWeight: '800', fontSize: 14 },
  secondaryBtn: {
    minHeight: 44,
    borderRadius: radii.pill,
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primarySoft,
    borderWidth: 1,
    borderColor: colors.primaryBorder,
  },
  secondaryBtnText: { color: colors.primaryDark, fontWeight: '800', fontSize: 13 },

  modalRoot: { flex: 1, backgroundColor: colors.background },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingHorizontal: spacing.screenX,
    paddingTop: 18,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.cardBorder,
    backgroundColor: colors.card,
  },
  modalClose: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalKicker: { fontSize: 11, fontWeight: '700', color: colors.primary, letterSpacing: 0.3 },
  modalTitle: { fontSize: 18, fontWeight: '900', color: colors.textStrong },
  modalScroll: { padding: spacing.screenX, paddingBottom: 40, gap: 14 },
  modalFooter: {
    padding: spacing.screenX,
    borderTopWidth: 1,
    borderTopColor: colors.cardBorder,
    backgroundColor: colors.card,
  },

  referenceCard: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: 16,
    gap: 6,
  },
  referenceLabel: { fontSize: 11, fontWeight: '700', color: colors.muted, letterSpacing: 0.3 },
  referenceValue: { fontSize: 17, fontWeight: '900', color: colors.textStrong, letterSpacing: 0.4 },

  metaLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceMuted,
  },
  metaLabel: { fontSize: 12, fontWeight: '600', color: colors.muted, flex: 0.45 },
  metaValue: {
    fontSize: 13,
    fontWeight: '700',
    color: colors.textStrong,
    flex: 0.55,
    textAlign: 'right',
  },

  historyItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceMuted,
    gap: 2,
  },
  historyTitle: { fontSize: 13, fontWeight: '800', color: colors.textStrong },
  historyMeta: { fontSize: 12, color: colors.muted, lineHeight: 17 },
  linkRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceMuted,
  },
});
