import FontAwesome from '@expo/vector-icons/FontAwesome';
import { router, useLocalSearchParams } from 'expo-router';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { circleWorkspaceHref, myCirclesHref } from '@/lib/navigation';
import { colors, radii, spacing } from '@/lib/theme';

/**
 * Legacy route: circle history now lives in the Records statement center.
 * This screen redirects users into the workspace Records tab.
 */
export default function CircleHistoryScreen() {
  const params = useLocalSearchParams<{ circleId?: string | string[] }>();
  const circleId = Array.isArray(params.circleId)
    ? params.circleId[0]
    : params.circleId;

  function openRecords() {
    if (circleId) {
      router.replace(circleWorkspaceHref(circleId, 'records'));
      return;
    }
    router.replace(myCirclesHref);
  }

  function handleBack() {
    if (circleId) {
      router.replace(circleWorkspaceHref(circleId));
      return;
    }
    router.replace(myCirclesHref);
  }

  return (
    <SafeAreaView style={styles.screen} edges={['top', 'left', 'right']}>
      <ScrollView contentContainerStyle={styles.content}>
        <View style={styles.header}>
          <Pressable
            style={styles.backButton}
            onPress={handleBack}
            accessibilityRole="button"
            accessibilityLabel={
              circleId ? 'Back to circle workspace' : 'Back to My Circles'
            }
          >
            <FontAwesome name="angle-left" size={24} color={colors.primaryDark} />
          </Pressable>
          <View style={styles.headerCopy}>
            <Text style={styles.kicker}>Circle records</Text>
            <Text style={styles.title}>Statement center</Text>
          </View>
        </View>

        <View style={styles.card}>
          <Text style={styles.eyebrow}>Moved</Text>
          <Text style={styles.cardTitle}>
            History and statements live in Records
          </Text>
          <Text style={styles.body}>
            Use the circle workspace Records tab for Circle Records, Member
            Statements, and Documents. Member Circle Statements are generated by
            the backend from permission-filtered snapshots — not a bank statement,
            tax document, or proof of income.
          </Text>
          <Pressable
            style={styles.primaryButton}
            onPress={openRecords}
            accessibilityRole="button"
            accessibilityLabel="Open Records"
          >
            <Text style={styles.primaryButtonText}>
              {circleId ? 'Open Records' : 'Back to My Circles'}
            </Text>
          </Pressable>
        </View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingBottom: 40,
    paddingHorizontal: spacing.screenX,
    paddingTop: 18,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.card,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  headerCopy: {
    flex: 1,
  },
  kicker: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  title: {
    color: colors.textStrong,
    fontSize: 24,
    fontWeight: '900',
    marginTop: 2,
  },
  card: {
    backgroundColor: colors.card,
    borderRadius: radii.card,
    borderWidth: 1,
    borderColor: colors.cardBorder,
    padding: spacing.card,
  },
  eyebrow: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '800',
    marginBottom: 8,
  },
  cardTitle: {
    color: colors.textStrong,
    fontSize: 18,
    fontWeight: '900',
    marginBottom: 8,
  },
  body: {
    color: colors.muted,
    fontSize: 14,
    lineHeight: 21,
    marginBottom: 18,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    borderRadius: radii.pill,
    paddingVertical: 14,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '800',
  },
});
